---
  main:
  dataset:
  training:
    --detection_to_evaluate:
      - pred_0
    --view_ids:
      - "0"
      - "1" 
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
    --metric_to_print:
      - moda_pred_0
      - recall_pred_0
      - precision_pred_0
    --loss_to_print:
      - loss_pred
      - loss_framepred
